### ISSUE TITLE
images should look clickable

### ISSUE THREAD

**Issue by jenweber** [tildeio/ember-women#11]
I didn't realize there were expanded details and bios until I had to fill out my own in the source data. Any ideas for how to clearly imply that there's more info?

Something along these lines could help, but this only works if someone actually hovers on them:
```
 .woman-thumb:hover{
       transform: scale(1.10);
       box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.26);
}
```

**Comment by wifelette** [comment]
@jeffdaley Thoughts?

**Comment by jeffdaley** [comment]
Yes, this should at least have a hover state. Here's a branch with a scale+opacity effect: https://github.com/tildeio/ember-women/pull/13

This seems pretty effective but let me know if I should explore designs with a stronger click affordance.

I wonder if we even need the descriptions behind a click. The EmberConf speakers page is a good reference: http://emberconf.com/speakers.html It's long but still manageable, even with two times the people.

**Comment by wifelette** [comment]
@jenweber I'll merge since this is surely better than _nothing_, but take a look at the PR once I redeploy (shortly) and let me know if you think this helps enough or if we should experiment a bit more :) I'll do the same.

**Comment by jenweber** [comment]
Looks great! I think the hover state helps a lot.
